### ISSUE TITLE
Lots of "Received passengers for unknown entity" in the console

### ISSUE THREAD

**Issue by Virtuoel** [ModFest/fireblanket#11]
![Received passengers for unknown entity](https://cdn.discordapp.com/attachments/368860033443954688/1142198164598816895/image.png)

![i think the received passengers thing is fair enough for a fix
can you open an issue](https://cdn.discordapp.com/attachments/368860033443954688/1142198656045424692/image.png)

**Comment by IThundxr** [comment]
this happens in ``` net.minecraft.client.multiplayer.ClientPacketListener
public void handleSetEntityPassengersPacket(ClientboundSetPassengersPacket packet )```

![](https://host.ithundxr.dev/r/Jfm4FV.png?compress=false)

**Comment by quat1024** [comment]
im guessing packets are getting shuffled out of order; a `ClientboundAddEntityPacket` of the vehicle has to come first so that the numeric ID for that entity gets allocated on the client, only then are other packets allowed to refer to it by that id

to some degree, this type of thing happens in vanilla (you will occasionally get `ClientboundRotateHeadPacket`s or `ClientboundSetEntityMotionPacket `s for entities the server hasn't told you to spawn yet)

**Comment by IThundxr** [comment]
> im guessing packets are getting shuffled out of order; a `ClientboundAddEntityPacket` of the vehicle has to come first so that the numeric ID for that entity gets allocated on the client, only then are other packets allowed to refer to it by that id
> 
> 
> 
> to some degree, this type of thing happens in vanilla (you will occasionally get `ClientboundRotateHeadPacket`s or `ClientboundSetEntityMotionPacket `s for entities the server hasn't told you to spawn yet)

This is just create trains this could be cause of the compression but I swear I've seen this before even without it so just silencing these would probably be the best option
